#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 16 21:20:00 JST 2024
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim crypto_sign_verify_tb_behav -key {Behavioral:sim_1:Functional:crypto_sign_verify_tb} -tclbatch crypto_sign_verify_tb.tcl -view /usr/luan_home2/Kiet/project_2/crypto_sign_keypair_tb_behav.wcfg -log simulate.log"
xsim crypto_sign_verify_tb_behav -key {Behavioral:sim_1:Functional:crypto_sign_verify_tb} -tclbatch crypto_sign_verify_tb.tcl -view /usr/luan_home2/Kiet/project_2/crypto_sign_keypair_tb_behav.wcfg -log simulate.log

